freebsd/crochet

board/Wandboard/files/boot.txt, board/Wandboard/setup.sh
0x88000000 is too large for Dual and Solo boards.
Also fixes some typos copying dtb files.
=> Wandboard: Use 0x11000000 as the ubldr load address

lib/freebsd.sh
This fixes build when world has libraries that are built with different options than in the
default src.conf (like nandfs, etc).
=> Add SRCCONF and __MAKE_CONF to ubldr environment

lib/freebsd.sh
This makes the log look more like the rest of the messages.. i.e.
This:
```Installing ubldr in /home/brd/crochet/work/_.mount.boot```
Instead of:
```Installing ubldr in .```
=> Give a proper path when installing ubldr

board/Cubieboard2/setup.sh, config.sh.sample
- Update KERNCONF
- Fix the config.sh.sample name to match the directory exactly
=> Fixes for Cubieboard2

board/RaspberryPi/overlay/etc/ttys, board/RaspberryPi2/overlay/etc/ttys
When using `dialup` terminal type, some applications that "draw" stuff on the screen don't work like: `edit`, `nano`, `tmux`, or any `ncurses` application. This is fixed by changing the terminal type to `vt100` in `/etc/ttys` so those types of applications may run "out of the box."
=> Change default terminal to vt100 for RPi boards

lib/disk.sh, lib/freebsd.sh
This comes into play when /home is a symlink to /usr/home.  Otherwise
the path in /usr/obj/usr/home/${USER}/crochet path doesn't match.
=> Fix ${FREEBSD_OBJDIR}

board/Alix/setup.sh
Installing bootblocks
Boot files are at: /root/crochet-master/work/obj/i386.i386/usr/srcsys/boot/i386
gpart: /root/crochet-master/work/obj/i386.i386/usr/srcsys/boot/i386/mbr/mbr: No such file or directory
=> Fixed an issue with missing trailing / of objdir variable.

lib/disk.sh, lib/freebsd.sh
Efi partition was written to a local file. Added "/dev/" to efi partition variable to make correct efi device.
Kern/worldjobs did not work when defined in config.sh. Variables where rewritten (to -jx) too early before they had been set by the config file, moved to build() functions.
=> Corrected EFI partition and WORLDJOBS/KERNJOBS variable

option/User/setup.sh
Use
option User username group1 group2 ...
to create a user and add to secondary groups.
This uses 'pw' instead of editing group file with sed directly.
=> Add user to groups

option/PackageInit/setup.sh
`etc/pkg/tmp.conf` might be missing when using default FreeBSD package site
=> Fix package init cleanup

lib/disk.sh
Building a Raspberry Pi 3 image on FreeBSD 11.0-RELEASE-p8 the FAT partition created contains 8+3 all _UPPERCASE_ letters, rendering image unbootable.
By adding `-l` flag to `mount_msdosfs` command, it forced the long filenames.
=> Force long filenames on FAT partition

board/BananaPi-M3/setup.sh, board/BananaPi/setup.sh, board/Cubieboard2/setup.sh, board/OrangePi-Plus2E/setup.sh
As the result of [r431327](https://svnweb.freebsd.org/ports?view=revision&revision=431327) in ports.
Also use conv=notrunc,sync when writing, as mentioned in https://github.com/freebsd/crochet/issues/191#issuecomment-313300456.
Fixes #190 
Fixes #191
=> rename sunxi-spl.bin to u-boot-sunxi-with-spl.bin on all Allwinner boards

board/Pine64/setup.sh
Updated board/Pine64/setup.sh to work after the latest Pine64 u-boot.  Adresses #201
=> Fix for Pine64 (u-boot-pine64-2017.07.00.1) update

config.sh.sample, lib/board.sh
The board_setup function now saves the board's name to BOARDNAME, and
board_generate_image_name will later use it to add it to the image's name.
For https://github.com/freebsd/crochet/issues/207
=> [Issue-207] By default add the name of the board to the image's name

board/Pine64/setup.sh
We don't hold arm64 dts in-tree anymore, so this step is not needed.
=> Fix Pine64 build

board/RaspberryPiCM3L/README, board/RaspberryPiCM3L/overlay/boot/loader.conf, board/RaspberryPiCM3L/overlay/boot/loader.rc, board/RaspberryPiCM3L/overlay/etc/fstab, board/RaspberryPiCM3L/overlay/etc/rc.conf, board/RaspberryPiCM3L/setup.sh, config.sh.sample
These commits add a directory for the Raspberry Pi Compute Module 3 Lite and create README and setup.sh files for the CM3. The setup script is mostly identical to the RPi3 setup script except that a different device tree is fetched and the `sysutils/rpi-firmware` port is used for firmware instead of `sysutils/u-boot-rpi3`. The `u-boot-rpi3` firmware does not seem to select the correct device tree during boot whereas `rpi-firmware` does. 
EDIT: The image that this generates also works on the Raspberry Pi Compute Module 3 (with eMMC), with two caveats: 
1. Size: the image size must be kept <4GB since the Compute Module 3 only has 4GB of embedded flash.
2. Difficult to flash eMMC: [The official method for flashing the CM3](https://www.raspberrypi.org/documentation/hardware/computemodule/cm-em …
=> Support for Raspberry Pi Compute Module 3 Lite

board/RaspberryPi2/setup.sh
Its hard to find a micro SD or flash smaller than 4GB.  The RPi3 image
no longer fits in 2GB so 3GB seem like a reasonable choice.
=> increase IMAGE_SIZE for RaspberryPi2 to 3GB

board/OrangePi-One/opione-workaround.dts, board/OrangePi-One/overlay/etc/fstab, board/OrangePi-One/overlay/etc/rc.conf, board/OrangePi-One/setup.sh
This board directory has been in use for about two weeks.  A number of
ports built on an Orange Pi PC Plus have been tested on this platform
and work.  Both use the armv7 architecture but TARGET_ARCH is set to
armv6 so there may be room for improvement.
=> checkout for board directory for Orange Pi One

board/RaspberryPi2/setup.sh
Recently ports sysutils/rpi-firmware and sysutils/u-boot-rpi2 was updated to newer versions. After this updates crochet must install more files on boot partition to make FreeBSD bootable on Raspberry Pi 2 again.
=> Make bootable on Raspberry Pi 2 with recent rpi-firmware & u-boot-rpi2

board/RaspberryPi2/setup.sh
Raspberry Pi 2 is using Cortex-a7 cpu, so it's a good idea to optimize system for that.
According to nbench, with this optimization system is 3% faster in integer aritmetic and 21% faster in floating-point.
=> Use better optimization for Raspberry Pi 2

board/Pine64/setup.sh
Now "sudo ./crochet.sh -b Pine64" will get a 2.2G img.
=> Pine64: image size increase to 3G

board/NanoPi-R4S/README, board/NanoPi-R4S/overlay/boot/loader.conf, board/NanoPi-R4S/overlay/etc/fstab, board/NanoPi-R4S/overlay/etc/rc.conf, board/NanoPi-R4S/setup.sh
This has been tested with FreeBSD 13.0-RELEASE and current. Board support is generally quite good and upstream u-boot supports it since 2021.07.
There also exists a 1GB/DDR3 variant of the board which upstream u-boot does not support (yet) but it looks like it is not sold anymore - so sorry for anyone that has bought the 1GB variant.
Bootlog is available at:
https://people.freebsd.org/~decke/nanopi-r4s/friendlyelec-nanopi-r4s-bootlog.txt
=> NanoPi R4S: Add support for FriendlyElec Nano-Pi R4S (rk3399)

board/OrangePi-One/README
This board (Orange Pi One) works fine with no dts workaround needed (other than HDMI due to unsupported GPU).  README file describes the board, it's status, and gives build instructions.
=> Add a README file to the OrangePi-One board directory

board/OrangePi-PC-Plus/README
The README does give a status which is essentially untested since I
accidentally tested with an OrangePi-PC card and don't have an
OrangePi-PC-Plus handy (yet).  When I get one I'll update the status
and make any changes as needed.
=> Add a README file to the OrangePi-PC-Plus directory

option/User/setup.sh
Corrected strategy_add from BOARD_INSTALL to OPTION_INSTALL (otherwise it will be run before pkg install). 
Added create group if does not exist.
=> Fixes to User

board/RaspberryPi3/setup.sh
Using FreeBSD 15.0 source, the aarch64 build with 32-bit compat support does not fit in the freebsd ufs partition when the overall image/disk size is restricted to 3GB.
=> Increase RaspberryPi3 IMAGE_SIZE to 4GB

board/Pine64-LTS/README, board/Pine64-LTS/overlay/boot/loader.rc, board/Pine64-LTS/overlay/etc/fstab, board/Pine64-LTS/overlay/etc/rc.conf, board/Pine64-LTS/setup.sh
based on Pine64 board directory
image size increased to ((3000 * 1000 * 1000))
use u-boot-sopine rather than u-boot-pine64 due to type of DRAM used
using the u-boot-pine64 fails to detect any DRAM in u-boot startup
=> Add Pine64-LTS board directory

board/OrangePi-PC/README, board/OrangePi-PC/opipc-workaround.dts, board/OrangePi-PC/overlay/etc/fstab, board/OrangePi-PC/overlay/etc/rc.conf, board/OrangePi-PC/setup.sh
A workaround is needed in the dts file to avoid the pcm0 device.  The
HDMI doesn't work as with all H3 cards until the ARM Mali-400 GPU is
supported in FreeBSD.
=> Initial commit of OrangePi-PC board directory

board/RaspberryPi4/README, board/RaspberryPi4/overlay/boot/loader.conf, board/RaspberryPi4/overlay/boot/loader.rc, board/RaspberryPi4/overlay/etc/fstab, board/RaspberryPi4/overlay/etc/rc.conf, board/RaspberryPi4/setup.sh, lib/disk.sh
Base support on the RaspberryPi3 crochet flow but use the correct firmware binaries and device-tree bindings.
=> RaspberryPi4: Implement initial support

board/BananaPi/setup.sh
Fix for failing bananapi boot, see #281 for explaination.
=> Bananapi: add boot script for uboot
